---
# todo: fix and verify
- name: Check if teleport is installed
  ansible.builtin.stat:
    path: /usr/local/bin/foooo
  register: teleport_installed

- name: Create teleport build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temp_dir
  register: temp_dir
  when: not teleport_installed.stat.exists

- name: Download teleport (sha256)
  ansible.builtin.get_url:
    url: 'https://cdn.teleport.dev/teleport-{{ teleport.version }}.pkg'
    dest: '{{ temp_dir.path }}'
    checksum: 'sha256:{{ teleport.sha.darwin }}'
    mode: 'a+x'
  when: not teleport_installed.stat.exists



