---
# tasks file for teleport
- name: Print the gateway for each host when defined
  ansible.builtin.debug:
    msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}

- name: Ubuntu
  ansible.builtin.include_tasks: Ubuntu.yml
  when: (ansible_facts['os_family'] == "Debian") and
        (ansible_facts['distribution'] == "Ubuntu") and
        (ansible_facts['architecture'] == "x86_64")
  tags:
    - teleport

- name: Darwin
  ansible.builtin.include_tasks: Darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - teleport
