---
- name: Import Teleport's PGP public key
  ansible.builtin.get_url:
    url: https://apt.releases.teleport.dev/gpg
    dest: /etc/apt/trusted.gpg.d/teleport.asc
    owner: root
    group: root
    mode: '0644'
  become: true
  tags:
    - teleport

- name: Import Teleport repo
  ansible.builtin.apt_repository:
    repo: >
      deb [signed-by=/etc/apt/trusted.gpg.d/teleport.asc]
      https://apt.releases.teleport.dev/ubuntu {{ ansible_facts.distribution_release }}
      stable/v11
    state: present
    filename: /etc/apt/sources.list.d/teleport
  become: true
  tags:
    - teleport

- name: Install teleport
  ansible.builtin.apt:
    pkg:
      - teleport
    update_cache: true
    state: present
  become: true
  tags:
    - teleport
