---
# tasks file for terraform
- name: Tap a Homebrew terraform repository, state present
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present

- name: Install terraform
  community.general.homebrew:
    name: hashicorp/tap/terraform
    state: present
    update_homebrew: true

- name: Install aquasecurity/tfsec
  community.general.homebrew:
    name: tfsec
    state: present
    update_homebrew: true

- name: Install terraform-linters/tflint
  community.general.homebrew:
    name: tflint
    state: present
    update_homebrew: true
