---
- name: Check if VScode is installed
  ansible.builtin.stat:
    path: /Applications/Visual Studio Code.app
  register: code_installed

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temp_dir
  register: temp_dir
  when: not code_installed.stat.exists

- name: Download VScode
  ansible.builtin.get_url:
    url: https://code.visualstudio.com/sha/download?build=stable&os=darwin
    dest: '{{ temp_dir.path }}/Visual Studio Code.zip'
    mode: '0744'
  when: not code_installed.stat.exists

- name: Unarchive VScode to Applications
  ansible.builtin.unarchive:
    src: '{{ temp_dir.path }}/Visual Studio Code.zip'
    dest: /Applications/
    remote_src: true
  when: not code_installed.stat.exists

- name: Remove the temporary dir
  ansible.builtin.file:
    path: '{{ temp_dir.path }}'
    state: absent
  when: temp_dir.path is defined
