---
# tasks file for kubernetes-resource-advisor
- name: Ubuntu
  ansible.builtin.include_tasks: Ubuntu-x86_64.yml
  when: (ansible_facts['os_family'] == "Debian") and
        (ansible_facts['distribution'] == "Ubuntu") and
        (ansible_facts['architecture'] == "x86_64")
  tags:
    - kubernetes
    - resources
    - resource-advisor

- name: Darwin
  ansible.builtin.include_tasks: Darwin-x86_64.yml
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - kubernetes
    - resources
    - resource-advisor
