---
# ansible-playbook --ask-become-pass -e user=$USER playbook.yaml
- name: Setup workstation
  hosts: localhost
  gather_facts: true
  roles:
    - argo
    - aws
    - azure
    - brave
    - cmctl
    - copper
    - docker
    - doctl
    - firewall
    - gcp
    - git
    - github
    - helm
    - k6s
    - keepassxc
    - kind
    - kube_bench
    - kube_hunter
    - kube_linter
    - kubectl
    - kubesquash
    - logcli
    - open_lens
    - open_policy_agent
    # todo:- pcloud
    - stern
    - syncthing
    - teleport
    - telepresence
    - terraform
    - tilt
    - usb_display_link
    - velero
    - vscode
    - wireguard
    - zsh
