---
# ansible-playbook --ask-become-pass -e user=$USER playbook.yaml
- name: Setup workstation
  hosts: localhost
  gather_facts: true
  roles:
    - display_link
    - open_lens
    - argo
    - aws
    - azure
    - brave
    - cmctl
    - copper
    - display_link
    - docker
    - doctl
    # - falco
    - firewall
    - gcp
    - git
    - github
    - helm
    - k6s
    - keepassxc
    - kind
    # - kube_bench
    # - kube_hunter
    # - kube_linter
    - kubectl
    # - kubesquash
    - logcli
    - open_lens
    # - open_policy_agent
    # - pcloud
    - stern
    - syncthing
    - teleport
    - telepresence
    - terraform
    - tilt
    - velero
    - vscode
    - wireguard
    - zsh
