---
# ansible-playbook --ask-become-pass -e user=$USER playbook.yaml
- name: Setup workstation
  hosts: localhost
  gather_facts: true
  roles:
   - firewall
   - docker
   - zsh
   - git
   - aws
   - azure
   - doctl
   - gcp
   - kubectl
   - helm
   - terraform
   - tilt
   - teleport
   - telepresenc
   - argo
   - velero
   - cmctl
   - logcli
   - k6s
   - kind
   - github
   - kube_bench
   - stern
   - copper
   - keepassxc
   - syncthing
   - wireguard
   - vscode
   - brave
   - open_lens
   # todo: kube-linter
   # todo: open policy agent
   # todo: kube-hunter
   # todo: kubesquash
   # todo: falco
