---
- name: Prepare
  hosts: all
  tasks:
    - name: Update repositories cache and install "gzip" package
      ansible.builtin.apt:
        pkg:
          - gzip
          - unzip
        update_cache: true
        state: present
      become: true
