---
# tasks file for azure
- name: Install az
  community.general.homebrew:
    name: azure-cli
    state: present
    update_homebrew: true
  tags: azure-cli

- name: Install kubelogin
  community.general.homebrew:
    name: kubelogin
    state: present
    update_homebrew: true
  tags: kubelogin

- name: Install Azure VPN Client
  block:
    - name: Install mas
      community.general.homebrew:
        name: mas
        state: present
        update_homebrew: true

    - name: Install Azure VPN Client
      community.general.mas:
        id:
          - 1553936137
        state: latest
  tags: azureVPNclient

- name: Install Azure Storage Explorer
  block:
    - name: Check if Azure Storage Explorer is installed
      ansible.builtin.stat:
        path: /usr/local/bin/kubelogin
      register: ase_installed

    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
        suffix: temp_dir
      register: temp_dir
      when: not ase_installed.stat.exists

    - name: Download Azure Storage Explorer (sha256)
      ansible.builtin.get_url:
        url: 'https://go.microsoft.com/fwlink/?linkid=2216184'
        dest: '{{ temp_dir.path }}'
        mode: '0744'
      when: not ase_installed.stat.exists

    # todo: fix
    # - name: Unarchive Azure Storage Explorer
    #  ansible.builtin.unarchive:
    #    src: '{{ temp_dir.path }}/kubelogin-linux-amd64.zip'
    #    dest: '{{ temp_dir.path }}'
    #    remote_src: true
    #  when: not ase_installed.stat.exists

    # - name: Install Azure Storage Explorer
    #  ansible.builtin.copy:
    #    src: '{{ temp_dir.path }}/bin/linux_amd64/kubelogin'
    #    dest: /usr/local/bin/kubelogin
    #    owner: '{{ user }}'
    #    mode: 'a+x'
    #    remote_src: true
    #  become: true
    #  when: not ase_installed.stat.exists

    - name: Remove the temporary dir
      ansible.builtin.file:
        path: '{{ temp_dir.path }}'
        state: absent
      when: temp_dir.path is defined
  become: true
  tags:
    - azure-storage-explorer
