---
# tasks file for azure
- name: Install az
  community.general.homebrew:
    name: azure-cli
    state: present
    update_homebrew: true
  tags: azure-cli

- name: Install kubelogin
  community.general.homebrew:
    name: kubelogin
    state: present
    update_homebrew: true
  tags: kubelogin

- name: Install Azure VPN Client
  block:
    - name: Install mas
      community.general.homebrew:
        name: mas
        state: present
        update_homebrew: true

    - name: Install Azure VPN Client
      community.general.mas:
        id:
          - 1553936137
        state: latest
  tags: azureVPNclient
