---
# tasks file for doctl
- name: Ubuntu
  ansible.builtin.include_tasks: Ubuntu-x86_64.yml
  when: (ansible_facts['os_family'] == "Debian") and
        (ansible_facts['distribution'] == "Ubuntu") and
        (ansible_facts['architecture'] == "x86_64")
  tags:
    - unbound

- name: Darwin
  ansible.builtin.include_tasks: Darwin.yml
  when: (ansible_facts['os_family'] == "Darwin") and
        (ansible_facts['architecture'] == "x86_64")
  tags:
    - unbounds

