---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Ubuntu
    image: ubuntu
    privileged: true
  - name: Ubuntu-lts
    image: ubuntu:22.04
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: ansible
