---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Ubuntu
    image: ubuntu
    privileged: true
  - name: Ubuntu-lts
    image: ubuntu:22.04
    privileged: true
  # - name: macosx
  #   box: yzgyyang/macOS-10.14
  #   memory: 2048
  #   cpus: 1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: ansible
