---
- name: Uninstall old docker versions
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    purge: true
  become: true

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temp_dir
  register: temp_dir

- name: Setup Docker-CE
  block:
    - name: Fetch Docker CE official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.gpg
        owner: root
        group: root
        mode: 'a+r'

    - name: Import Docker CE repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: /etc/apt/sources.list.d/docker-ce
  become: true

- name: Install Docker CE
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - docker-compose-plugin
  become: true

- name: Created docker group
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Restart docker service
  ansible.builtin.service:
    state: restarted
    name: docker
  become: true
  ignore_errors: true

- name: Remove the temporary dir
  ansible.builtin.file:
    path: '{{ temp_dir.path }}'
    state: absent
  when: temp_dir.path is defined
