---
- name: Uninstall old docker versions
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    purge: true
  become: true

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temp_dir
  register: temp_dir

- name: Download Docker CE official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: '{{ temp_dir.path }}/docker.gpg'
    mode: '0777'

- name: Save Docker CE official GPG key
  ansible.builtin.shell: 'cat {{ temp_dir.path }}/docker.gpg | gpg --dearmor > /etc/apt/trusted.gpg.d/docker.gpg'
  become: true

- name: Import Docker CE repo
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker
    content: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release|string }} stable'
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install Docker CE
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - docker-compose-plugin
  become: true

- name: Created docker group
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Enable overlay2 driver
  ansible.builtin.copy:
    content: '{  \"storage-driver\": \"overlay2\" }'
    dest: /etc/docker/daemon.json
  become: true

- name: Restart docker service
  ansible.builtin.group.systemd:
    state: restarted
    name: docker
  become: true

- name: Remove the temporary dir
  ansible.builtin.file:
    path: '{{ temp_dir.path }}'
    state: absent
  when: temp_dir.path is defined
