---
- name: Uninstall old docker versions
  ansible.builtin.apt:
    name:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
    state: absent
    purge: true
  become: true

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Import Docker’s repo
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release|string }} stable'
    state: present
  become: true

- name: Install docker
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
  become: true