---
- name: Import Syncthing's PGP public key
  ansible.builtin.get_url:
    url: https://syncthing.net/release-key.txt
    dest: /etc/apt/trusted.gpg.d/syncthing.txt
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Import Syncthing repo
  ansible.builtin.apt_repository:
    repo: >
      deb [signed-by=/etc/apt/trusted.gpg.d/syncthing.txt]
      https://apt.syncthing.net/ syncthing release
    state: present
    filename: /etc/apt/sources.list.d/syncthing
  become: true

- name: Update repositories cache and install "syncthing" package
  ansible.builtin.apt:
    name: syncthing
    update_cache: true
  become: true
