---
- name: Import Syncthing public key
  ansible.builtin.apt_key:
    url: https://syncthing.net/release-key.txt
    state: present
  become: true

- name: Import Syncthing repo
  ansible.builtin.apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing release
    state: present
    filename: /etc/apt/sources.list.d/syncthing.list
  become: true