---
# tasks file for stern
- name: Check if stern is installed
  ansible.builtin.stat:
    path: /usr/local/bin/stern
  register: stern_installed

- name: Install tar
  community.general.homebrew:
    name: gnu-tar
    state: present
    update_homebrew: true

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temp_stern
  register: temp_dir
  when: not stern_installed.stat.exists

- name: Download stern (sha)
  ansible.builtin.get_url:
    url: 'https://github.com/stern/stern/releases/download/v{{ stern.version }}/stern_{{ stern.version }}_darwin_amd64.tar.gz'
    dest: '{{ temp_dir.path }}'
    checksum: 'sha256:{{ stern.sha.amd64.darwin }}'
    mode: '0744'
  when: not stern_installed.stat.exists

- name: Unarchive stern
  ansible.builtin.unarchive:
    src: '{{ temp_dir.path }}/stern_{{ stern.version }}_darwin_amd64.tar.gz'
    dest: '{{ temp_dir.path }}'
    remote_src: true
  when: not stern_installed.stat.exists

- name: Install stern cli
  ansible.builtin.copy:
    src: '{{ temp_dir.path }}/stern'
    dest: /usr/local/bin/stern
    owner: root
    mode: a+x
    remote_src: true
  become: true
  when: not stern_installed.stat.exists

- name: Remove the temporary dir
  ansible.builtin.file:
    path: '{{ temp_dir.path }}'
    state: absent
  when: temp_dir.path is defined
