- name: Install a rclone.deb package from the internet
  ansible.builtin.apt:
    deb: https://downloads.rclone.org/v1.63.0/rclone-v1.63.0-linux-amd64.deb
  become: true

- name: Setup .rclone.conf for {{ user }}
  ansible.builtin.blockinfile:
    path: /home/{{ user }}/.config/rclone/rclone.conf
    create: true
    group: '{{ user }}'
    owner: '{{ user }}'
    mode: 'a+x'
    block: |
      [aws]
      type = s3
      provider = AWS
      env_auth = true
      region = eu-west-2
      storage_class = STANDARD