---
- name: Prepare
  hosts: all
  tasks:
    - name: Update repositories cache and install "gpg-agent" package
      ansible.builtin.apt:
        pkg:
          - gpg-agent
        update_cache: true
        state: present
      become: true
