---
# tasks file for argo
- name: Check if argo cli is installed
  ansible.builtin.stat:
    path: /usr/local/bin/argo
  register: argo_installed

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temp_dir
  register: temp_dir
  when: not argo_installed.stat.exists

- name: Download argo cli (sha256)
  ansible.builtin.get_url:
    url: https://github.com/argoproj/argo-workflows/releases/download/v{{ argo.version }}/argo-linux-amd64.gz
    dest: '{{ temp_dir.path }}'
    checksum: sha256:{{ argo.sha }}
    mode: '0777'
  when: not argo_installed.stat.exists

- name: Unarchive
  ansible.builtin.command: 'gunzip {{ temp_dir.path }}/argo-linux-amd64.gz'
  when: not argo_installed.stat.exists

- name: Install argo cli
  ansible.builtin.copy:
    src: '{{ temp_dir.path }}/argo-linux-amd64'
    dest: /usr/local/bin/argo
    owner: root
    group: root
    mode: a+x
    remote_src: true
  become: true
  when: not argo_installed.stat.exists

- name: Remove the temporary dir
  ansible.builtin.file:
    path: '{{ temp_dir.path }}'
    state: absent
  when: temp_dir.path is defined
