---
- name: Prepare
  hosts: all
  tasks:
    - name: Update repositories cache and install "gpg" and "dirmngr" packages
      ansible.builtin.apt:
        pkg:
          - gpg
          - dirmngr
        update_cache: true
        state: present
      become: true
