---
# tasks file for telepresence
- name: Install telepresence.io
  community.general.homebrew:
    name: datawire/blackbird/telepresence
    state: present
    update_homebrew: true
  tags:
    - telepresence