---
- name: Check if datree is installed
  stat:
    path: /usr/local/bin/datree
  register: datree_installed

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temp_dir
  register: temp_dir
  when: not datree_installed.stat.exists

- name: Download datree (sha256)
  ansible.builtin.get_url:
    url: 'https://github.com/datreeio/datree/releases/download/{{ datree.version }}/datree-cli_{{ datree.version }}_Linux_x86_64.zip'
    dest: '{{ temp_dir.path }}'
    checksum: 'sha256:{{ datree.sha.amd64.linux }}'
    mode: a+x
  when: not datree_installed.stat.exists

- name: Unarchive datree
  ansible.builtin.unarchive:
    src: '{{ temp_dir.path }}/datree-cli_{{ datree.version }}_Linux_x86_64.zip'
    dest: '{{ temp_dir.path }}'
    remote_src: true
  when: not datree_installed.stat.exists

- name: Install datree
  ansible.builtin.copy:
    src: '{{ temp_dir.path }}/datree'
    dest: /usr/local/bin/datree
    owner: root
    group: root
    mode: a+x
    remote_src: true
  become: true
  when: not datree_installed.stat.exists

- name: Remove the temporary dir
  ansible.builtin.file:
    path: '{{ temp_dir.path }}'
    state: absent
  when: temp_dir.path is defined
