---
- name: Prepare
  hosts: all
  tasks:
    - name: Update repositories cache and install "gpg" and "curl" package
      ansible.builtin.apt:
        pkg:
          - gpg
          - curl
        update_cache: true
        state: present
      become: true
