---
- name: Install displaylink requirements
  ansible.builtin.apt:
    pkg:
      - dkms
      - libdrm-dev
    update_cache: true
    state: present
  become: true

- name: Install, configure, displaylink
  block:
    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
        suffix: temp_dir
      register: temp_dir

    - name: Download displaylink (sha256)
      ansible.builtin.get_url:
        url: https://www.synaptics.com/sites/default/files/exe_files/2022-08/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu5.6.1-EXE.zip
        dest: '{{ temp_dir.path }}'
        checksum: 'sha256:89279748a9e276073ddfff7e949f2b92e30dc19f29a34c40ffcd3356c6d730c2'
        mode: '0777'

    - name: Unarchive displaylink
      ansible.builtin.unarchive:
        src: '{{ temp_dir.path }}/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu5.6.1-EXE.zip'
        dest: '{{ temp_dir.path }}'
        mode: 'a+x'
        remote_src: true

    - name: Install displaylink
      ansible.builtin.command: '{{ temp_dir.path }}/displaylink-driver-5.6.1-59.184.run'

    - name: Remove the temporary dir
      ansible.builtin.file:
        path: '{{ temp_dir.path }}'
        state: absent
      when: temp_dir.path is defined

  # when: not display_link_installed.stat.exists
  become: true
