#!/usr/bin/env bash

if git commit -v --dry-run | grep '!nocommit' >/dev/null 2>&1
then
  echo "Trying to commit non-committable code."
  echo "Remove the !nocommit string and try again."
  exit 1
else
  # Run local pre-commit hook if exists
  if [ -e ./.git/hooks/pre-commit ]; then
    ./.git/hooks/pre-commit "$@"
  else
    exit 0
  fi
fi

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

gittyleaks --no-banner --verbose

git secrets --pre_commit_hook -- "$@"

git-secrets --scan --recursive

trufflehog git file://. --since-commit HEAD --only-verified --fail
trufflehog filesystem --directory=. --fail
yamllint -f auto .