#!/usr/bin/env bash

echo "linting"
hadolint ${$(find . -type f -name "Dockerfile"):-"-v"}
yamllint -f auto $(find . -type f -regex '.*ya?ml*')

echo "checking for secrets..."
trufflehog git $(git config --get remote.origin.url) --no-update --since-commit HEAD --fail --concurrency=12

if git commit -v --dry-run | grep '!nocommit' >/dev/null 2>&1
then
  echo "Trying to commit non-committable code."
  echo "Remove the !nocommit string and try again."
  exit 1
else
  # Run local pre-commit hook if exists
  if [ -e ./.git/hooks/pre-commit ]; then
    ./.git/hooks/pre-commit "$@"
  else
    exit 0
  fi
fi

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2