---
- name: Converge
  hosts: all
  gather_facts: true
  environment:
    SYSTEMINITDAEMON: systemd
  tasks:
    - name: "Include display USB link"
      include_role:
        name: "usb_display_link"
