---
# tasks file for cert-manager
- name: Ubuntu
  ansible.builtin.include_tasks: Ubuntu-x86_64.yml
  when: (ansible_facts['os_family'] == "Debian") and
        (ansible_facts['distribution'] == "Ubuntu") and
        (ansible_facts['architecture'] == "x86_64")
  tags:
    - cert-manager-cli

- name: Darwin
  ansible.builtin.include_tasks: Darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - cert-manager-cli
