---
- name: Prepare
  hosts: all
  tasks:
    - name: Update repositories cache and install packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - curl
        update_cache: true
        state: present
      become: true
