---
# tasks file for gcp
- name: Ubuntu
  ansible.builtin.include_tasks: Ubuntu.yml
  when: (ansible_facts['os_family'] == "Debian") and
        (ansible_facts['distribution'] == "Ubuntu")
  tags:
    - unbound

- name: Darwin
  ansible.builtin.include_tasks: Darwin-x86_64.yml
  when: (ansible_facts['os_family'] == "Darwin") and
        (ansible_facts['architecture'] == "x86_64")
  tags:
    - unbounds
