---
- name: Import Google Cloud public key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/trusted.gpg.d/google.gpg
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Import Google Cloud repo
  ansible.builtin.copy:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
    state: present
    filename: /etc/apt/sources.list.d/google-cloud-sdk
  become: true

- name: Install google-cloud-sdk
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
    pkg:
      - google-cloud-sdk
  become: true
