---
# tasks file for open-lens
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temp_dir
  register: temp_dir
  when: not ansible_facts.packages['open-lens'] is defined

- name: Download openLens file with check (sha256)
  ansible.builtin.get_url:
    url: 'https://github.com/MuhammedKalkan/OpenLens/releases/download/v{{ open_lens.version }}/OpenLens-{{ open_lens.version }}.amd64.deb'
    dest: '{{ temp_dir.path }}'
    checksum: 'sha256:{{ open_lens.sha.deb }}'
    mode: '0777'
  when: not ansible_facts.packages['open-lens'] is defined

- name: Install a openLens.deb package
  ansible.builtin.apt:
    deb: '{{ temp_dir.path }}/OpenLens-{{ open_lens.version }}.amd64.deb'
  become: true
  when: not ansible_facts.packages['open-lens'] is defined

- name: Remove the temporary dir
  ansible.builtin.file:
    path: '{{ temp_dir.path }}'
    state: absent
  when: temp_dir.path is defined
