---
- name: Add the yubico software repository
  ansible.builtin.apt_repository:
    repo: ppa:yubico/stable
    state: present
  become: true

- name: Update repositories cache and install packages
  ansible.builtin.apt:
    pkg:
      - software-properties-common
      - wget
      - gnupg2
      - gnupg-agent
      - dirmngr
      - cryptsetup
      - scdaemon
      - pcscd
      - secure-delete
      - hopenpgp-tools
      - yubikey-personalization
      - yubioath-desktop
      - yubikey-luks
      - yubikey-manager
      - libssl-dev
      - swig
      - libpcsclite-dev
      - python3-pip
      - python3-pyscard
    update_cache: true
    state: present
  become: true

# - name: Install ykman
#   ansible.builtin.pip:
#     name:
#       - PyOpenSSL
#     executable: pip

- name: Restart service pcscd, in all cases
  ansible.builtin.service:
    name: pcscd
    state: restarted
  become: true

- name: Setup gpg-agent.conf for {{ user }}
  ansible.builtin.blockinfile:
    path: /home/{{ user }}/.gnupg/gpg-agent.conf
    create: true
    group: '{{ user }}'
    owner: '{{ user }}'
    mode: 'a+x'
    block: |
      # https://github.com/drduh/config/blob/master/gpg-agent.conf
      # https://www.gnupg.org/documentation/manuals/gnupg/Agent-Options.html
      enable-ssh-support
      default-cache-ttl 60
      max-cache-ttl 120
      # pinentry-program /usr/bin/pinentry-curses
      pinentry-program /usr/bin/pinentry-gnome3

- name: Configure GPG as SSH agent
  block:
    - name: Create required directories
      file:
        path: '{{ item }}'
        state: directory
        mode: '0700'
      loop:
        - /home/{{ user }}/.config/autostart
        - /home/{{ user }}/.config/environment.d

    - name: Disable Gnome-Keyring ssh component
      copy:
        src: /etc/xdg/autostart/gnome-keyring-ssh.desktop
        dest: /home/{{ user }}/.config/autostart/gnome-keyring-ssh.desktop
        mode: '0644'

    - name: Hide Gnome-Keyring ssh component
      lineinfile:
        path: /home/{{ user }}/.config/autostart/gnome-keyring-ssh.desktop
        line: "Hidden=true"

    - name: Point ssh agent socket environment variable to GnuPG
      copy:
        dest: /home/{{ user }}/.config/environment.d/99-gpg-agent_ssh.conf
        content: |
          SSH_AUTH_SOCK=${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh
        mode: '0644'

    - name: Display final message
      debug:
        msg: "Restart your computer and then GnuPG will be your ssh-agent"