---
- name: Update repositories cache and install packages
  ansible.builtin.apt:
    pkg:
      - software-properties-common
      - wget
      - gnupg2
      - gnupg-agent
      - dirmngr
      - cryptsetup
      - scdaemon
      - pcscd
      - secure-delete
      - hopenpgp-tools
      - yubikey-personalization
      - yubioath-desktop
      - yubikey-luks
      - libssl-dev
      - swig
      - libpcsclite-dev
      - python3-pip
      - python3-pyscard
    update_cache: true
    state: present
  become: true

- name: Install ykman
  ansible.builtin.pip:
    name:
      - PyOpenSSL
      - yubikey-manager
    executable: pip3

- name: Restart service pcscd, in all cases
  ansible.builtin.service:
    name: pcscd
    state: restarted
  become: true

- name: Test openpgp info
  ansible.builtin.command: '/home/{{ user }}/.local/bin/ykman openpgp info'

- name: Setup gpg-agent.conf for {{ user }}
  ansible.builtin.blockinfile:
    path: /home/{{ user }}/.gnupg/gpg-agent.conf
    create: true
    group: '{{ user }}'
    owner: '{{ user }}'
    mode: 'a+x'
    block: |
      # https://github.com/drduh/config/blob/master/gpg-agent.conf
      # https://www.gnupg.org/documentation/manuals/gnupg/Agent-Options.html
      enable-ssh-support
      default-cache-ttl 60
      max-cache-ttl 120
      pinentry-program /usr/bin/pinentry-curses
