---
- name: Check if velero is installed
  ansible.builtin.stat:
    path: /usr/local/bin/velero
  register: velero_installed

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temp_dir
  register: temp_dir
  when: not velero_installed.stat.exists

- name: Download Velero with check (sha256)
  ansible.builtin.get_url:
    url: https://github.com/vmware-tanzu/velero/releases/download/v{{ velero.version }}/velero-v{{ velero.version }}-darwin-amd64.tar.gz
    dest: '{{ temp_dir.path }}/linux-amd64.tar.gz'
    checksum: sha256:f2e1a91663b631626ae255a46d1e422406a338336d106e899f9cb1cde7455090
    mode: '0744'
  when: not velero_installed.stat.exists

- name: Download Velero
  ansible.builtin.unarchive:
    src: '{{ temp_dir.path }}/linux-amd64.tar.gz'
    dest: '{{ temp_dir.path }}'
    remote_src: true
  when: not velero_installed.stat.exists

- name: Install Velero
  ansible.builtin.copy:
    src: '{{ temp_dir.path }}/velero-v{{ velero.version }}-linux-amd64/velero'
    dest: /usr/local/bin/velero
    owner: root
    group: root
    mode: a+x
    remote_src: true
  become: true
  when: not velero_installed.stat.exists

- name: Remove the temporary dir
  ansible.builtin.file:
    path: '{{ temp_dir.path }}'
    state: absent
  when: temp_dir.path is defined
