---
# tasks file for velero
- name: Ubuntu
  ansible.builtin.include_tasks: Ubuntu-x86_64.yml
  when: (ansible_facts['os_family'] == "Debian") and
        (ansible_facts['distribution'] == "Ubuntu") and
        (ansible_facts['architecture'] == "x86_64")
  tags:
    - kubernetes
    - vector

- name: Darwin
  ansible.builtin.include_tasks: Darwin-x86_64.yml
  when: (ansible_facts['os_family'] == "Darwin") and
        (ansible_facts['architecture'] == "x86_64")
  tags:
    - kubernetes
    - vector
