---
- name: Import keepassxc repo
  ansible.builtin.apt_repository:
    repo: ppa:phoerious/keepassxc
  become: true

- name: Update repositories cache and install "keepassxc" package
  ansible.builtin.apt:
    name: keepassxc
    update_cache: yes