---
- name: Check if opa is installed
  stat:
    path: /usr/local/bin/opa
  register: opa_installed

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temp_dir
  register: temp_dir
  when: not opa_installed.stat.exists

- name: Download opa (sha256)
  ansible.builtin.get_url:
    url: 'https://github.com/open-policy-agent/opa/releases/download/v{{ opa.version }}/opa_darwin_amd64'
    dest: '{{ temp_dir.path }}'
    checksum: 'sha256:{{ opa.sha.amd64.darwin }}'
    mode: 'a+x'
  when: not opa_installed.stat.exists

- name: Install opa
  ansible.builtin.copy:
    src: '{{ temp_dir.path }}/opa_darwin_amd64'
    dest: /usr/local/bin/opa
    owner: '{{ user }}'
    mode: 'a+x'
    remote_src: true
  become: true
  when: not opa_installed.stat.exists

- name: Remove the temporary dir
  ansible.builtin.file:
    path: '{{ temp_dir.path }}'
    state: absent
  when: temp_dir.path is defined
