---
# tasks file for helm
- name: Ubuntu
  ansible.builtin.include_tasks: Ubuntu-x86_64.yml
  when: (ansible_facts['os_family'] == "Debian") and
        (ansible_facts['distribution'] == "Ubuntu") and
        (ansible_facts['architecture'] == "x86_64")
  tags:
    - helm
    - helmfile

- name: Darwin
  ansible.builtin.include_tasks: Darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - helm
    - helmfile

- name: Install helm-diff
  ansible.builtin.command: helm plugin list | grep diff || helm plugin install https://github.com/databus23/helm-diff
  changed_when: false
  tags:
    - helm

- name: Add helm repos
  ansible.builtin.command: 'helm repo add {{ item }}'
  loop:
    - "vmware-tanzu https://vmware-tanzu.github.io/helm-charts"
    - "jetstack https://charts.jetstack.io"
    - "nginx-stable https://helm.nginx.com/stable"
    - "nginx https://kubernetes.github.io/ingress-nginx"
    - "azuredisk-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts"
    - "aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver"
    - "aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver"
    - "prometheus-community https://prometheus-community.github.io/helm-charts"
    - "grafana https://grafana.github.io/helm-charts"
    - "vector https://helm.vector.dev"
    - "victoria-metrics https://victoriametrics.github.io/helm-charts"
    - "elastic https://helm.elastic.co"
    - "bitnami https://charts.bitnami.com/bitnami"
    - "teleport https://charts.releases.teleport.dev"
    - "istio https://istio-release.storage.googleapis.com/charts"
    - "kiali https://kiali.org/helm-charts"
    - "chaos-mesh https://charts.chaos-mesh.org"
    - "aquasecurity https://aquasecurity.github.io/helm-charts"
    - "aqua-helm https://helm.aquasec.com"
    - "stakater https://stakater.github.io/stakater-charts"
    - "hashicorp https://helm.releases.hashicorp.com"
    - "external-secrets https://charts.external-secrets.io"
    - "kubernetes-dashboard https://kubernetes.github.io/dashboard"
    - "backstage https://backstage.github.io/charts"
    - "sloth https://slok.github.io/sloth"
    - "crossplane-stable https://charts.crossplane.io/stable"
    - "crossplane-master https://charts.crossplane.io/master"
    - "kubescape https://kubescape.github.io/helm-charts"
    - "kyverno https://kyverno.github.io/kyverno"
    - "kubeclarity https://openclarity.github.io/kubeclarity"
  changed_when: false
  tags:
    - helm

- name: Update helm repos
  ansible.builtin.command: 'helm repo update'
  changed_when: false
  tags:
    - helm
