---
# tasks file for brave
- name: Import Brave public key
  ansible.builtin.apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    keyring: /etc/apt/trusted.gpg.d/brave-browser-release.gpg
    state: present
  become: true

- name: Import Brave repo
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/brave-browser-release
    content: 'deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main'
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install Brave
  ansible.builtin.apt:
    pkg:
      - brave-browser
    update_cache: true
    state: present
  become: true
