---
# tasks file for brave
- name: Import Brave public key
  ansible.builtin.apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    keyring: /etc/apt/trusted.gpg.d/brave-browser-release.gpg
    state: present
  become: true

- name: Import Brave repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/brave-browser-release.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present
    filename: /etc/apt/sources.list.d/brave-browser-release
  become: true

- name: Install Brave
  ansible.builtin.apt:
    pkg:
      - brave-browser
    update_cache: true
    state: present
  become: true
