---
# tasks file for aws
- name: Ubuntu
  ansible.builtin.include_tasks: Ubuntu.yml
  when: (ansible_facts['os_family'] == "Debian") and
        (ansible_facts['distribution'] == "Ubuntu")
  tags:
    - aws

- name: Darwin
  ansible.builtin.include_tasks: Darwin.yml
  when: (ansible_facts['os_family'] == "Darwin") and
        (ansible_facts['architecture'] == "x86_64")
  tags:
    - aws
