---
# tasks file for git
- name: Install git
  community.general.homebrew:
    name: git
    state: present
    update_homebrew: true

- name: Install trufflehog
  community.general.homebrew:
    name: trufflehog
    state: present
    update_homebrew: true

- name: Install git-secrets
  community.general.homebrew:
    name: git-secrets
    state: present
    update_homebrew: true

- name: Copy global gitIgnore
  ansible.builtin.copy:
    src: '{{ role_path }}/files/gitIgnore'
    dest: '/Users/{{ user }}/.gitIgnore'
    group: '{{ user }}'
    owner: '{{ user }}'
    mode: a+x

- name: Create gitHooks directory (.gitHooks)
  ansible.builtin.file:
    path: '/Users/{{ user }}/.gitHooks'
    state: directory
    group: '{{ user }}'
    owner: '{{ user }}'
    mode: '0755'

- name: Copy global gitHooks
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/Users/{{ user }}/.gitHooks'
    group: '{{ user }}'
    owner: '{{ user }}'
    mode: a+x
  with_fileglob:
    - '{{ role_path }}/files/hooks/*'

- name: Check if /home/{{ user }}/.gitconfig exists
  ansible.builtin.stat:
    path: /home/{{ user }}/.gitconfig
  register: gitconfig_installed

- name: Setting Up global Git
  ansible.builtin.blockinfile:
    path: /Users/{{ user }}/.gitconfig
    create: true
    owner: '{{ user }}'
    mode: a+x
    block: |
      [user]
          name = {{ user }}
      [core]
          hooksPath = /Users/{{ user }}/.gitHooks
          excludesfile = /Users/{{ user }}/.gitIgnore
      [safe]
        directory = /github/workspace
