---
# tasks file for git
- name: Install pre-commit and gittyleaks
  ansible.builtin.pip:
    name:
      - gittyleaks
      - pre-commit
    executable: pip3
  become: true
  tags:
    - git

- name: Ubuntu
  ansible.builtin.include_tasks: Ubuntu.yml
  when: (ansible_facts['os_family'] == "Debian") and
        (ansible_facts['distribution'] == "Ubuntu")
  tags:
    - git
    - git-secrets
    - git-config
    - git-hooks
    - git-ignore
    - trufflehog
    - hadolint

- name: Darwin
  ansible.builtin.include_tasks: Darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - git
    - git-secrets
    - git-config
    - git-hooks
    - git-ignore
    - trufflehog
    - hadolint
