---
# tasks file for git
- name: Install gittyleaks for Python 3 user in git pre-commit
  ansible.builtin.pip:
    name: gittyleaks
    executable: pip3
  become: true

- name: Ubuntu
  ansible.builtin.include_tasks: Ubuntu.yml
  when: (ansible_facts['os_family'] == "Debian") and
        (ansible_facts['distribution'] == "Ubuntu")
  tags:
    - unbound

- name: Darwin
  ansible.builtin.include_tasks: Darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - unbounds
