---
# tasks file for kubectl
- name: Ubuntu
  ansible.builtin.include_tasks: Ubuntu-x86_64.yml
  when: (ansible_facts['os_family'] == "Debian") and
        (ansible_facts['distribution'] == "Ubuntu") and
        (ansible_facts['architecture'] == "x86_64")
  tags:
    - kubernetes
    - kubectl
    - krew
    - kubesec

- name: Darwin
  ansible.builtin.include_tasks: Darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - kubernetes
    - kubectl
    - krew
    - kubesec

- name: Add krew indexes
  ansible.builtin.command: 'kubectl krew index add {{ item }}'
  loop:
    - kubevpn https://github.com/KubeNetworks/kubevpn.git
  changed_when: false
  tags:
    - krew

- name: Install kubectl plugins with krew
  ansible.builtin.command: 'krew install {{ item }}'
  loop:
    - blame
    - cert-manager
    - datree
    - debug-shell
    - images
    - istiolog
    - janitor
    - ktop
    - kubescape
    - kubesec-scan
    - mtail
    - popeye
    - score
    - starboard
    - tap
    - who-can
    - whoami
    - kyverno
    - kubevpn/kubevpn
  changed_when: false
  tags:
    - krew
