---
# tasks file for kubectl
- name: Ubuntu
  ansible.builtin.include_tasks: Ubuntu-x86_64.yml
  when: (ansible_facts['os_family'] == "Debian") and
        (ansible_facts['distribution'] == "Ubuntu") and
        (ansible_facts['architecture'] == "x86_64")
  tags:
    - kubernetes
    - kubectl
    - krew
    - kubesec

- name: Darwin
  ansible.builtin.include_tasks: Darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - kubernetes
    - kubectl
    - krew
    - kubesec

- name: Add krew indexes
  ansible.builtin.command: 'krew index add {{ item }}'
  loop:
    - "kubevpn https://github.com/KubeNetworks/kubevpn.git"
    - "default https://github.com/kubernetes-sigs/krew-index.git"
  changed_when: false
  ignore_errors: true
  tags:
    - krew

- name: Update krew indexes
  ansible.builtin.command: 'krew update'
  changed_when: false
  ignore_errors: true
  tags:
    - krew

- name: Install kubectl plugins with krew
  ansible.builtin.command: 'krew install {{ item }}'
  loop:
    - advise-policy
    - access-matrix
    - blame
    - cert-manager
    - cilium
    - datree
    - debug-shell
    - images
    - istiolog
    - janitor
    - ktop
    - kubectl-capture
    - kubectl-login
    - kubescape
    - kubesec-scan
    - mtail
    - popeye
    - score
    - starboard
    - stern
    - tap
    - trace
    - who-can
    - np-viewer
    - rolesum
    - rbac-tool
    - whoami
    - kyverno
    - kubevpn/kubevpn
  changed_when: false
  ignore_errors: true
  tags:
    - krew
