- name: Install datagrip
  community.general.snap:
    name:
      - datagrip
    classic: true
  become: true

- name: Install a go-migrate.deb package from the internet
  ansible.builtin.apt:
    deb: https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.deb
  become: true

- name: Install postgres15
  block:
  - name: Import postgres public key
    ansible.builtin.get_url:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      dest: /etc/apt/trusted.gpg.d/pgdg.asc
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: Import postgres repo
    ansible.builtin.apt_repository:
      repo: deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
      state: present
      filename: /etc/apt/sources.list.d/pgdg.list
    become: true

  - name: Update repositories cache and install "postgresql-*" packages
    ansible.builtin.apt:
      pkg:
        - postgresql-client
        - postgresql-client-common
        - libpq-dev
      update_cache: true
      state: present

  become: true