---
# tasks file for github-act
- name: Check if ACT cli is installed
  ansible.builtin.stat:
    path: /usr/local/bin/act
  register: act_installed

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temp_dir
  register: temp_dir
  when: not act_installed.stat.exists

- name: Download act cli (sha256)
  ansible.builtin.get_url:
    url: 'https://github.com/nektos/act/releases/download/v{{ act.version }}/act_Linux_x86_64.tar.gz'
    dest: '{{ temp_dir.path }}'
    checksum: 'sha256:{{ act.sha }}'
    mode: '0777'
  when: not act_installed.stat.exists

- name: Unarchive act
  ansible.builtin.unarchive:
    src: '{{ temp_dir.path }}/act_Linux_x86_64.tar.gz'
    dest: '{{ temp_dir.path }}'
    remote_src: true
  when: not act_installed.stat.exists

- name: Install act cli
  ansible.builtin.copy:
    src: '{{ temp_dir.path }}/act'
    dest: /usr/local/bin/act
    owner: root
    group: root
    mode: a+x
    remote_src: true
  become: true
  when: not act_installed.stat.exists

- name: Remove the temporary dir
  ansible.builtin.file:
    path: '{{ temp_dir.path }}'
    state: absent
  when: temp_dir.path is defined

- name: Add key for Github CLI software repository
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/trusted.gpg.d/githubcli.gpg
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Add the Github CLI software repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/github-cli
    line: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/githubcli.gpg] https://cli.github.com/packages stable main"
    create: true
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Get Github package
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
    pkg:
      - gh
  become: true
