name: CI
on:
  pull_request:
  push:
    branches:
    - '**'
  schedule:
    - cron: "30 5 * * 0"

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install test dependencies.
      run: pip3 install yamllint
    - name: Lint code.
      run: |
        yamllint .
    - name: Run ansible-lint
      uses: ansible/ansible-lint-action@main

  molecule:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        roles:
          - argo
          - aws
          - azure
          - brave
          - cmctl
          - copper
          - doctl
          - firewall
          - gcp
          - git
          - github
          - helm
          - k6s
          - keepassxc
          - kind
          - kube_bench
          - kubectl
          - kubesquash
          - logcli
          - stern
          - syncthing
          - teleport
          - telepresence
          - terraform
          - tilt
          - velero
          - vscode
          - wireguard
          - zsh

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Set up Python 3.
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: gofrolist/molecule-action@v2
      with:
        molecule_command: test
        molecule_working_dir: ${{ matrix.roles }}
      env:
        ANSIBLE_FORCE_COLOR: '1'
