name: CI
on:
  pull_request:
  push:
    branches:
    - '**'
  schedule:
    - cron: "30 5 * * 0"

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install test dependencies.
      run: pip3 install yamllint
    - name: Lint code.
      run: |
        yamllint .
    - name: Run ansible-lint
      uses: ansible/ansible-lint-action@main

  molecule-install-test:
    runs-on: ubuntu-latest
    #needs: lint
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        roles:
          - argo
          - firewall

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Set up Python 3.
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate current sha for role ${{ matrix.roles }}
      run: | 
        find ${{ matrix.roles }} -type f -print0 | xargs -0 sha1sum | sha1sum | awk '{print $1;}' > ${{ matrix.roles }}.sha
        cat ${{ matrix.roles }}.sha

    - uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.roles }}.sha
        path: ${{ matrix.roles }}_working.sha
      continue-on-error: true # Artifact may be missing or deleted

    - name: Check Working SHA for ${{ matrix.roles }}
      id: CheckWorkingSHA
      run: |
        FILE=${{ matrix.roles }}_working.sha
        if test -f "$FILE"; then
            echo "$FILE exists."
            VAR1=`cat ${{ matrix.roles }}_working.sha`
            VAR2=`cat ${{ matrix.roles }}.sha`
            if [ "$VAR1" = "$VAR2" ]; then
                echo "Strings are equal."
                exit 0
            else
                echo "Strings are not equal."
                exit 1
            fi
        else
          echo "working sha missing."
          exit 2
        fi
      continue-on-error: true # Artifact may be missing or deleted

    - name: Test
      if: steps.CheckWorkingSHA.outcome == 'failure'
      run: |
        echo "Run molecule test"

    #- name: Update working sha for role ${{ matrix.roles }}
    #  uses: actions/cache/save@v3
    #  with:
    #    path: ${{ matrix.roles }}.sha
    #    key: ${{ matrix.roles }}


    #- name: Cache roles sha
    #  id: cache-roles-sha
    #  uses: actions/cache@v3
    #  with:
    #    path: roles-sha
    #    key: ${{ matrix.roles }}-sha
    #- uses: gofrolist/molecule-action@v2
    #  timeout-minutes: 20
    #  with:
    #    molecule_command: test --destroy=never
    #    molecule_working_dir: ${{ matrix.roles }}
    #  env:
    #    ANSIBLE_FORCE_COLOR: '1'
    #- name: Upload Artifact
    #  if: github.ref == 'refs/heads/main'
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: ${{ matrix.roles }} role
    #    path: ${{ matrix.roles }}
    #    retention-days: 90
    #- name: Setup tmate session
    #  if: ${{ failure() }}
    #  uses: mxschmitt/action-tmate@v3
    #  timeout-minutes: 10
