---
# tasks file for k6s
- name: Ubuntu
  ansible.builtin.include_tasks: Ubuntu.yml
  when: (ansible_facts['os_family'] == "Debian") and
        (ansible_facts['distribution'] == "Ubuntu")
  tags:
    - k6s

- name: Darwin
  ansible.builtin.include_tasks: Darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - k6s
