---
- name: Import k6s key
  ansible.builtin.apt_key:
    id: C5AD17C747E3415A3642D57D77C6C491D6AC1D69
    keyserver: keyserver.ubuntu.com
    keyring: /etc/apt/trusted.gpg.d/k6s.gpg
    state: present
  become: true

- name: Import k6s repo
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/k6
    content: 'deb https://dl.k6.io/deb stable main'
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install k6s
  ansible.builtin.apt:
    pkg:
      - k6
    update_cache: true
    state: present
  become: true
